#ifndef PUREDARWIN_HOST_OS_AVAILABILITY_H
#define PUREDARWIN_HOST_OS_AVAILABILITY_H

#define API_AVAILABLE(...)
#define API_DEPRECATED(...)
#define API_DEPRECATED_WITH_REPLACEMENT(...)
#define API_UNAVAILABLE(...)
#define SPI_AVAILABLE(...)
#define SPI_DEPRECATED(...)
#define SPI_DEPRECATED_WITH_REPLACEMENT(...)

#endif
