add_subdirectory(corecrypto)
add_subdirectory(Libsystem)
add_subdirectory(Libdyld)
add_subdirectory(libblocks)
add_subdirectory(libm)
add_subdirectory(Libdispatch)
add_subdirectory(Liblaunch)
add_subdirectory(Libnotify)
add_subdirectory(Libasl)
add_subdirectory(Libinfo)
add_subdirectory(libc)
add_subdirectory(libplatform)
add_subdirectory(libmalloc)
add_subdirectory(libsystem_kernel)
add_subdirectory(pthread)

add_custom_target(base_system_runtime DEPENDS
    dispatch
    libdyld
    liblaunch
    libsystem_asl
    libsystem_blocks
    libsystem_c
    libsystem_darwin
    libsystem_info
    libsystem_kernel
    libsystem_m
    libsystem_malloc
    libsystem_notify
    libsystem_platform
    libsystem_pthread)
