# Mach-O CPU identity of the Darwin target, derived from the target triple.
# Host tools that inspect or emit Mach-O (libstuff, the CTF tools) use these to
# select the target slice, regardless of the machine they are running on.
if(NOT PUREDARWIN_TARGET_TRIPLE OR PUREDARWIN_TARGET_TRIPLE MATCHES "^(x86_64|amd64)-")
    set(PUREDARWIN_TARGET_CPU_TYPE CPU_TYPE_X86_64)
    set(PUREDARWIN_TARGET_CPU_SUBTYPE CPU_SUBTYPE_X86_64_ALL)
elseif(PUREDARWIN_TARGET_TRIPLE MATCHES "^(arm64|aarch64)-")
    set(PUREDARWIN_TARGET_CPU_TYPE CPU_TYPE_ARM64)
    set(PUREDARWIN_TARGET_CPU_SUBTYPE CPU_SUBTYPE_ARM64_ALL)
else()
    message(FATAL_ERROR "Cannot derive a Mach-O CPU type from PUREDARWIN_TARGET_TRIPLE \"${PUREDARWIN_TARGET_TRIPLE}\"")
endif()

function(target_darwin_platform name)
    if(PUREDARWIN_TARGET_TRIPLE)
        target_compile_options(${name} PRIVATE --target=${PUREDARWIN_TARGET_TRIPLE})
        target_link_options(${name} PRIVATE --target=${PUREDARWIN_TARGET_TRIPLE})
    endif()
endfunction()

function(add_darwin_executable name)
    cmake_parse_arguments(SL "NO_STANDARD_LIBRARIES;USE_HOST_SDK" "MACOSX_VERSION_MIN" "" ${ARGN})

    add_executable(${name})
    target_darwin_platform(${name})
    add_dependencies(${name} host_ld)
    target_compile_definitions(${name} PRIVATE __PUREDARWIN__)
    target_link_options(${name} PRIVATE -fuse-ld=$<TARGET_FILE:host_ld>)

    if(NOT SL_USE_HOST_SDK)
        target_compile_options(${name} PRIVATE -nostdlib -nostdinc)
        target_link_options(${name} PRIVATE -nostdlib)
        set_property(TARGET ${name} PROPERTY OSX_ARCHITECTURES x86_64)
    endif()

    # TODO: Handle SL_NO_STANDARD_LIBRARIES here, once the libraries have been added to the build.

    if(SL_MACOSX_VERSION_MIN)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${SL_MACOSX_VERSION_MIN})
    elseif(CMAKE_MACOSX_MIN_VERSION)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${CMAKE_MACOSX_MIN_VERSION})
    else()
        message(AUTHOR_WARNING "Could not determine -mmacosx-version-min flag for target ${name}")
    endif()
endfunction()

function(add_darwin_static_library name)
    cmake_parse_arguments(SL "USE_HOST_SDK" "MACOSX_VERSION_MIN" "" ${ARGN})

    add_library(${name} STATIC)
    target_darwin_platform(${name})
    add_dependencies(${name} host_libtool)
    target_compile_definitions(${name} PRIVATE __PUREDARWIN__)

    if(SL_MACOSX_VERSION_MIN)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${SL_MACOSX_VERSION_MIN})
    elseif(CMAKE_MACOSX_MIN_VERSION)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${CMAKE_MACOSX_MIN_VERSION})
    else()
        message(AUTHOR_WARNING "Could not determine -mmacosx-version-min flag for target ${name}")
    endif()

    if(NOT SL_USE_HOST_SDK)
        target_compile_options(${name} PRIVATE -nostdlib -nostdinc)
        set_property(TARGET ${name} PROPERTY OSX_ARCHITECTURES x86_64)
    endif()
endfunction()

function(add_darwin_shared_library name)
    cmake_parse_arguments(SL "MODULE;USE_HOST_SDK" "MACOSX_VERSION_MIN;INSTALL_NAME_DIR;INSTALL_NAME" "RPATHS" ${ARGN})

    if(SL_MODULE)
        add_library(${name} MODULE)
    else()
        add_library(${name} SHARED)
    endif()
    target_darwin_platform(${name})

    add_dependencies(${name} host_ld)
    target_link_options(${name} PRIVATE -fuse-ld=$<TARGET_FILE:host_ld>)
    target_compile_definitions(${name} PRIVATE __PUREDARWIN__)

    string(SUBSTRING ${name} 0 3 name_prefix)
    if(name_prefix STREQUAL "lib")
        string(SUBSTRING ${name} 3 -1 base_name)
        set_property(TARGET ${name} PROPERTY OUTPUT_NAME ${base_name})
        set_property(TARGET ${name} PROPERTY PREFIX lib)
    endif()
    set_property(TARGET ${name} PROPERTY SUFFIX .dylib)

    if(NOT SL_USE_HOST_SDK)
        target_compile_options(${name} PRIVATE -nostdlib -nostdinc)
        target_link_options(${name} PRIVATE -nostdlib)

        set_property(TARGET ${name} PROPERTY OSX_ARCHITECTURES x86_64)
    endif()

    if(SL_MACOSX_VERSION_MIN)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${SL_MACOSX_VERSION_MIN})
    elseif(CMAKE_MACOSX_MIN_VERSION)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${CMAKE_MACOSX_MIN_VERSION})
    else()
        message(AUTHOR_WARNING "Could not determine -mmacosx-version-min flag for target ${name}")
    endif()

    if(SL_INSTALL_NAME_DIR)
        target_link_options(${name} PRIVATE -install_name "${SL_INSTALL_NAME_DIR}/$<TARGET_FILE_NAME:${name}>")
        set_property(TARGET ${name} PROPERTY BUILD_WITH_INSTALL_NAME_DIR FALSE)
        set_property(TARGET ${name} PROPERTY NO_SONAME TRUE)
    elseif(SL_INSTALL_NAME)
        target_link_options(${name} PRIVATE -install_name ${SL_INSTALL_NAME})
        set_property(TARGET ${name} PROPERTY BUILD_WITH_INSTALL_NAME_DIR FALSE)
        set_property(TARGET ${name} PROPERTY NO_SONAME TRUE)
    elseif(NOT SL_MODULE)
        message(WARNING "Shared library target ${name} should have INSTALL_NAME_DIR defined")
    endif()

    foreach(rpath IN LISTS SL_RPATHS)
        target_link_options(${name} PRIVATE "SHELL:-rpath ${rpath}")
    endforeach()
endfunction()

function(add_darwin_object_library name)
    cmake_parse_arguments(SL "USE_HOST_SDK" "MACOSX_VERSION_MIN" "" ${ARGN})

    add_library(${name} OBJECT)
    target_darwin_platform(${name})
    set_property(TARGET ${name} PROPERTY LINKER_LANGUAGE C)
    target_compile_definitions(${name} PRIVATE __PUREDARWIN__)

    if(SL_MACOSX_VERSION_MIN)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${SL_MACOSX_VERSION_MIN})
    elseif(CMAKE_MACOSX_MIN_VERSION)
        set_property(TARGET ${name} PROPERTY CMAKE_OSX_DEPLOYMENT_TARGET ${CMAKE_MACOSX_MIN_VERSION})
    else()
        message(AUTHOR_WARNING "Could not determine -mmacosx-version-min flag for target ${name}")
    endif()

    if(NOT SL_USE_HOST_SDK)
        target_compile_options(${name} PRIVATE -nostdlib -nostdinc)
        set_property(TARGET ${name} PROPERTY OSX_ARCHITECTURES x86_64)
    endif()
endfunction()

set(CMAKE_SKIP_RPATH TRUE)
set(CMAKE_SKIP_BUILD_RPATH TRUE)
set(CMAKE_SKIP_INSTALL_RPATH TRUE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
set(CMAKE_MACOSX_RPATH FALSE)
